arm_pose:
  home :
  # joint name : angle(degree)
    joint1 : 0.0
    joint2 : -60
    joint3 : 20
    joint4 : 40
    gripper : 0.745  #0.013
    
  home_with_object :
    joint1 : 0.0
    joint2 : -35
    joint3 : 17.5
    joint4 : 17.5
      
  via_pose : 
    joint1 : 0.0
    joint2 : -18
    joint3 : 21
    joint4 : -3
    
  termination_pose :
    joint1 : 0.0
    joint2 : 0
    joint3 : 20
    joint4 : 70
  
approach:
  linear_vel : 0.05
  angular_vel : 0.1
  interval_sleep_ms : 500
  repeat_times : 2