arm_pose:
  home :
  # joint name : angle(degree)
    joint1 : 0.0
    joint2 : -60
    joint3 : 20
    joint4 : 40
    gripper : 0.745  #0.013
    
  home_with_object :
    joint1 : 0.0
    joint2 : -35    # 91.5
    joint3 : 17.5     # 268.75
    joint4 : 17.5     # 183.91
      
  via_pose : 
    joint1 : 0.0
    joint2 : -60
    joint3 : 20
    joint4 : 40
  
approach:
  linear_vel : 0.05
  angular_vel : 0.1
  interval_sleep_ms : 500